prSections:
    - title: My Pull Requests
      filters: is:open author:@me sort:updated-desc
      type: null
    - title: Needs My Review
      filters: is:open review-requested:@me sort:updated-desc
      type: null
    - title: Involved
      filters: is:open involves:@me -author:@me sort:updated-desc
      type: null
issuesSections:
    - title: My Issues
      filters: is:open author:@me
    - title: Assigned
      filters: is:open assignee:@me
    - title: Involved
      filters: is:open involves:@me -author:@me
repo:
    branchesRefetchIntervalSeconds: 30
    prsRefetchIntervalSeconds: 60
defaults:
    preview:
        open: true
        width: 70
    prsLimit: 20
    issuesLimit: 20
    view: prs
    layout:
        prs:
            updatedAt:
                width: 5
            createdAt:
                width: 5
            repo:
                width: 20
            author:
                width: 15
            assignees:
                width: 20
                hidden: true
            base:
                width: 15
                hidden: true
            lines:
                width: 15
        issues:
            updatedAt:
                width: 5
            createdAt:
                width: 5
            repo:
                width: 15
            creator:
                width: 10
            assignees:
                width: 20
                hidden: true
    refetchIntervalMinutes: 30
keybindings:
    universal: []
    issues: []
    prs:
        - key: v
          command: >
            cd {{.RepoPath}} &&
            code --profile "CodeReview" . &&
            gh pr checkout {{.PrNumber}}
    branches: []
repoPaths:
    :owner/:repo: ~/projects/:repo
    qroques/dotfiles: ~/dotfiles
theme:
    ui:
        sectionsShowCount: true
        table:
            showSeparator: true
            compact: true
    colors:
        text:
            primary: "#cdd6f4"
            secondary: "#fab387"
            inverted: "#11111b"
            faint: "#bac2de"
            warning: "#f38ba8"
            success: "#a6e3a1"
        background:
            selected: "#313244"
        border:
            primary: "#fab387"
            secondary: "#45475a"
            faint: "#313244"
pager:
    diff: ''
confirmQuit: false
