#!/bin/bash

sudo apt-get install python3-pip
sudo pip install --upgrade pip

sudo apt -y install zsh

git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k

chsh -s $(which zsh)
curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh | zsh

ln -s -f ~/dotfiles/system/.zshrc ~/.zshrc

mkdir ~/.fonts
wget https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf -P ~/.fonts/
wget https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold.ttf -P ~/.fonts/
wget https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Italic.ttf -P ~/.fonts/
wget https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold%20Italic.ttf -P ~/.fonts/
wget -P https://github.com/ryanoasis/nerd-fonts/releases/latest/download/Meslo.zip -P ~/.fonts/
unzip -d ~/.fonts ~/.fonts/Meslo.zip

# Other system commands
sudo apt -y install jq
sudo apt -y install curl
sudo apt -y install tmux
sudo apt -y install htop
sudo apt -y install flameshot
sudo snap install yq

git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf

sh ~/.fzf/install

# Install kitty conf
mkdir -p ~/.config/kitty
ln -s -f $PWD/system/kitty/kitty.conf $HOME/.config/kitty/kitty.conf

# Remove some gnome shortcuts
if [ $ORIGINAL_XDG_CURRENT_DESKTOP = 'ubuntu:GNOME' ]; then
    gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-down "[]"
    gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-up "[]"
    gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-down "[]"
    gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-up "[]"
    #Sceenshot
    gsettings set org.gnome.shell.keybindings show-screenshot-ui '[]'
    gsettings set org.gnome.settings-daemon.plugins.media-keys custom-keybindings "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/']"
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ name 'flameshot'
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ command '/usr/bin/flameshot gui'
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ binding 'Print'
fi
