#!/bin/bash

sudo apt -y install software-properties-common apt-transport-https wget
wget -q https://packages.microsoft.com/keys/microsoft.asc -O- | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
sudo apt install code

wget https://downloads.slack-edge.com/linux_releases/slack-desktop-4.10.0-amd64.deb
sudo apt install ./slack-desktop-4.10.0-amd64.deb

sudo apt install python3-pip
sudo pip install --upgrade pip
sudo pip install --upgrade awscli

sudo apt -y install ffmpeg
sudo add-apt-repository ppa:obsproject/obs-studio
sudo apt -y install obs-studio

//